/* 
    国家列表常量
*/

var country = [
  "Canada",
  "Great Britain",
  "USA",
  "The Whole World",
  "Afghanistan ",
  "Alabama",
  "Alaska",
  "Albania",
  "Alberta",
  "Algeria",
  "American Samoa ",
  "Andorra ",
  "Angola ",
  "Anguilla ",
  "Antigua and Barbuda ",
  "Argentina",
  "Arizona",
  "Arkansas",
  "Armenia",
  "Australia ",
  "Austria ",
  "Azerbaijan",
  "Azores (or Port) ",
  "Bahamas ",
  "Bahrain ",
  "Bangladesh ",
  "Barbados ",
  "Belarus",
  "Belgium",
  "Belize (former British Honduras)",
  "Benin (or Dahomey)",
  "Bermuda ",
  "Bhutan ",
  "Bolivia",
  "Bophuthatswana ",
  "Bosnia and Herzegowina",
  "Botswana ",
  "Brazil ",
  "British Columbia (CAN)",
  "Brunei ",
  "Bulgaria",
  "Burkina Fasso",
  "Burma ",
  "Burundi ",
  "California",
  "Cambodia ",
  "Cameroon ",
  "Canada",
  "Cape Verde Islands ",
  "Cayman Islands",
  "Central African Repub ",
  "Chad ",
  "Chile ",
  "China ",
  "Ciskei ",
  "Colombia ",
  "Colorado",
  "Comoro Island ",
  "Congo (Brazaville)",
  "Congo (former Zaire)",
  "Connecticut",
  "Cook Island ",
  "Costa Rica ",
  "Croatia",
  "Cuba ",
  "Cyprus ",
  "Czechoslovakia (former)",
  "Czech Republic",
  "Delaware",
  "Denmark ",
  "District of Columbia",
  "Djibouti (Jibuti)",
  "Dominica ",
  "Dominican Republic ",
  "Ecuador ",
  "Egypt ",
  "El Salvador ",
  "England ",
  "Equatorial Guinea ",
  "Eritrea",
  "Estonia ",
  "Ethiopia ",
  "Faeroe Islands ",
  "Falkland Island ",
  "Fiji ",
  "Finland ",
  "Florida",
  "France ",
  "French Guiana ",
  "French Kerguelen Islands",
  "French Polynesia ",
  "Gabon ",
  "Gambia ",
  "Georgia (Caucasus)",
  "Georgia (US)",
  "Germany ",
  "Ghana ",
  "Gibraltar ",
  "Great Britain",
  "Greece ",
  "Greenland ",
  "Grenada ",
  "Guadeloupe ",
  "Guam ",
  "Guatemala ",
  "Guernsey ",
  "Guinea ",
  "Guinea-Bissau ",
  "Guyana ",
  "Haiti ",
  "Hawaii",
  "Honduras ",
  "Hong Kong ",
  "Hungary ",
  "Iceland ",
  "Idaho",
  "Illinois",
  "India ",
  "Indiana",
  "Indonesia ",
  "Iowa",
  "Iran ",
  "Iraq ",
  "Ireland ",
  "Isle Of Man ",
  "Israel ",
  "Italy ",
  "Ivory Coast ",
  "Jamaica ",
  "Japan ",
  "Jersey ",
  "Jordan ",
  "Kansas",
  "Kazakhstan",
  "Kentucky",
  "Kenya ",
  "Kiribati ",
  "Korea (N and S) ",
  "Kosovo",
  "Kuwait ",
  "Kyrgyzstan",
  "Laos ",
  "Latvia ",
  "Lebanon ",
  "Lesotho ",
  "Liberia ",
  "Libya ",
  "Liechtenstein ",
  "Lithuania",
  "Louisiana",
  "Luxembourg ",
  "Macau ",
  "Macedonia",
  "Madagascar ",
  "Maine",
  "Malawi ",
  "Malaysia ",
  "Maldive Islands ",
  "Mali ",
  "Malta ",
  "Manitoba (CAN)",
  "Martinique ",
  "Maryland",
  "Massachusetts",
  "Mauritania ",
  "Mauritius ",
  "Mayotte ",
  "Mexico",
  "Michigan",
  "Midway Islands ",
  "Minnesota",
  "Mississippi",
  "Missouri",
  "Moldova",
  "Monaco",
  "Mongolia ",
  "Montana",
  "Montenegro",
  "Montserrat ",
  "Morocco ",
  "Mozambique ",
  "Muscat and Oman ",
  "Namibia",
  "Nauru ",
  "Nebraska",
  "Nepal ",
  "Netherlands ",
  "Netherlands Antilles ",
  "Nevada",
  "New Brunswick (CAN)",
  "New Caledonia ",
  "Newfoundland (CAN)",
  "New Hampshire",
  "New Jersey",
  "New Mexico",
  "New York",
  "New Zealand ",
  "Nicaragua ",
  "Niger ",
  "Nigeria ",
  "Niue ",
  "No Country",
  "Norfolk Islands ",
  "North Carolina",
  "North Dakota",
  "Northern Ireland ",
  "Northwest Territories (CAN)",
  "Norway ",
  "Nova Scotia (CAN)",
  "Ohio",
  "Oklahoma",
  "Ontario (CAN)",
  "Oregon",
  "Pacific Islands Trust Ter.",
  "Pakistan ",
  "Palestine ",
  "Panama ",
  "Papua ",
  "Paraguay ",
  "Pennsylvania",
  "Peru ",
  "Philippines ",
  "Pitcairn ",
  "Poland ",
  "Portugal ",
  "Prince Edward Island (CAN)",
  "Puerto Rico",
  "Qatar ",
  "Quebec (CAN)",
  "Reunion ",
  "Rhode Island",
  "Romania ",
  "Russian Federation",
  "Rwanda ",
  "San Marino ",
  "Sao Tome and Principe ",
  "Saskatchewan (CAN)",
  "Saudi Arabia ",
  "Scotland ",
  "Senegal ",
  "Serbia",
  "Seychelles ",
  "Sierra Leone ",
  "Singapore ",
  "Slovakia",
  "Slovenia",
  "Solomon Islands ",
  "Somalia ",
  "South Africa ",
  "South Carolina",
  "South Dakota",
  "South Georgia ",
  "Soviet Union (former)",
  "Spain ",
  "Sri Lanka ",
  "St Helena ",
  "St Kitts-Nevis ",
  "St Lucia ",
  "St Piere and Miquelon ",
  "St Vincent ",
  "Sudan ",
  "Surinam ",
  "Swaziland ",
  "Sweden ",
  "Switzerland ",
  "Syria ",
  "Taiwan ",
  "Tajikistan",
  "Tanzania ",
  "Tennessee",
  "Texas",
  "Thailand ",
  "Timor Leste",
  "Togo ",
  "Tokelau Island ",
  "Tonga ",
  "Transkei ",
  "Trinidad and Tobago ",
  "Tunisia ",
  "Turkey ",
  "Turkmenistan",
  "Turks and Caicos Islands ",
  "Tuvalu Islands ",
  "Uganda ",
  "Ukraine",
  "United Arab Emirates ",
  "Upper Volta (also Bkf) ",
  "Uruguay ",
  "USA",
  "Utah",
  "Uzbekistan",
  "Vanuatu ",
  "Venda ",
  "Venezuela ",
  "Vermont",
  "Vietnam ",
  "Virginia",
  "Virgin Islands ",
  "Wake Island ",
  "Wales ",
  "Wallis and Futuna ",
  "Washington",
  "Western Sahara",
  "Western Samoa ",
  "West Virginia",
  "Wisconsin",
  "Wyoming",
  "Yemen ",
  "Yugoslavia (former)",
  "Yukon Territories (CAN)",
  "Zambia ",
  "Zimbabwe  (former Rhodesia)"
]
export default country;
