/* 
    faq 相关常量数据
*/
 var  text = [
    {
      question: "What is Astromind?",
      answer:
        "Astromind is to conduct a psychological analysis project based on blockchain using big data and artificial intelligence.The cultivation of Astrobaby is combination of fostering fun and mind mapping, which is game for strangers to conduct social communication."
    },
    {
      question: "What is Astrobaby?",
      answer:
        "Astrobaby is produced from Astroegg, which would provide prediction and company for our game players."
    },
    {
      question: "What is the features of our game?",
      answer:
        "The information of players is stored on the blockchain that is decentralized so players do not need to worry about their privacy in the game. The emotional analysis is based on big data and artificial intelligence Dapp and cultivation are the core of the game. Astrobaby is cultivated with the information provided by the players."
    },
    {
      question: "What is ABC?",
      answer:
        "The full name of ABC is Astrobaby Coin, which is token used in the game and generated by smart contracts on the blockchain.Primarily, after ABC is generated, it would be assigned to certain accounts. In the initial stage of the game, each player could apply for three ABC.If players buy ABC, their accounts would be assigned certain tokens."
    },
    {
      question: "How to buy an Astroegg?",
      answer:
        "There is an address and an ID for every Astroegg and if there is a trade between owners and other players, the address and ID would be changed.Every ten minutes, there would an Astroegg produced. Players can participate in the draw but they have to freeze one ABC during the draw. One who get the Astobaby in the draw should pay the one ABC and the other would have 0.9 as refund."
    },
    {
      question: "Could Astrobaby reproduce?",
      answer:
        "Astrobaby is unique for every player and they do not reproduce generations."
    },
    {
      question: "Do I need to pay for it?",
      answer:
        "Only players in the early stage could have Astroegg(s), later players should pay for the ABC to buy Astroegg(s)."
    }
    
  ]

  export default text;